### ISSUE TITLE
Swift storage service has hardcoded secrets. These must be possible to pass in to the Swift container  as env variables.

### ISSUE THREAD

**Issue by jbernal0019** [FNNDSC/ChRIS_store#20]

**Comment by jennydaman** [comment]
Related repo: https://github.com/FNNDSC/docker-swift-onlyone

Task: allow the user and password of swift service to be customized, preferably using docker secrets. 
https://docs.docker.com/engine/swarm/secrets/

Docker secrets are (text) files made securely visible to containers under `/run/secret/<name>`. Example:

```yaml
version: '3.7'

services:
  swift:
    image: fnndsc/docker-swift-onlyone:latest
    init: true
    ports:
      - "8080:8080"
    volumes:
      - swift_storage:/srv
    secrets:
      - swift-credentials
    restart: unless-stopped

secrets:
  swift-credentials:
    file: ./my-swift-credentials.env
```
